### PR TITLE
Fix min_block_size

### PR DESCRIPTION
**Pull request by gongweibao**
According:https://github.com/PaddlePaddle/Paddle/issues/8638#issuecomment-369912156
We can use bandwidth efficiently when data size is larger than 2MB.

### CODE REVIEW

**Comment by typhoonzero** [comment]
1048576 float32 is 1MB

**Comment by gongweibao** [comment]
```
1048576 float32 is 1MB
```

It's the number of elements.

**Comment by gongweibao** [comment]
```
Can you give min_block_size default value internally?
```

I think it's better to allow the user to change it!

**Comment by typhoonzero** [comment]
It is, so if using float32, the size is 1MB not 2MB

**Comment by gongweibao** [comment]
```
It is, so if using float32, the size is 1MB not 2MB
```

4MB.

**Pull request merged**
